// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RappiFood_ApiRest.Data;

#nullable disable

namespace RappiFood_ApiRest.Migrations
{
    [DbContext(typeof(RappiFoodDbContext))]
    partial class RappiFoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RappiFood_ApiRest.Models.MenuRappiFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuRappiFoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Caldo de vegetales con albacora",
                            NameFood = "Encebollado",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Caldo frio con pescado curtido",
                            NameFood = "Cebiche de Pescado",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Verde cocinado en hoja relleno de pescado",
                            NameFood = "Bollo de Pescado",
                            Price = 1.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
